stages:
  - synchronization

variables:
  MIRROR_REPO: git@github.com:thm-projects/arsnova-microservices.git

sync_mirror:
  stage: synchronization
  when: always
  allow_failure: true
  script:
    - git clone --bare "$CI_REPOSITORY_URL" mirror.git
    - mkdir ~/.ssh && echo "$GITHUB_HOST_KEY" > ~/.ssh/known_hosts
    - eval $(ssh-agent -s) && ssh-add <(echo "$GITHUB_DEPLOY_KEY")
    - cd mirror.git
    - git update-ref -d refs/tags/production
    - git update-ref -d refs/tags/staging
    - git push --mirror "$MIRROR_REPO"
